---
substitutions:
  device_class1: 'water'
  device_class2: 'gas'

  device_icon1: 'mdi:water'
  device_icon2: 'mdi:meter-gas'

  volume_unit1: 'gal'
  volume_unit2: 'ft³'

  prefix1_name: 'Water '
  prefix1_id: 'water_'
  prefix2_name: 'Gas '
  prefix2_id: 'gas_'

  gpio_led: GPIO18

  i2c1_sda: GPIO2
  i2c1_scl: GPIO1
  i2c2_sda: GPIO4
  i2c2_scl: GPIO5

  flow_update_interval_seconds1: '10'
  flow_update_interval_seconds2: '30'

packages:
  meter1: !include
    file: esphome-magnetometer.yaml
    vars:
      device_class: ${device_class1}
      device_icon: ${device_icon1}
      volume_unit: ${volume_unit1}
      prefix_name: ${prefix1_name}
      prefix_id: ${prefix1_id}
      i2c_sda: ${i2c1_sda}
      i2c_scl: ${i2c1_scl}
      flow_update_interval_seconds: ${flow_update_interval_seconds1}
  meter2: !include
    file: esphome-magnetometer.yaml
    vars:
      device_class: ${device_class2}
      device_icon: ${device_icon2}
      volume_unit: ${volume_unit2}
      prefix_name: ${prefix2_name}
      prefix_id: ${prefix2_id}
      i2c_sda: ${i2c2_sda}
      i2c_scl: ${i2c2_scl}
      flow_update_interval_seconds: ${flow_update_interval_seconds2}

switch:
  # LED flashes faster/slower as magnet rotates on water meter
  - platform: gpio
    id: led
    pin:
      number: ${gpio_led}
      inverted: true
