---
esphome:
  name: water-meter
  friendly_name: Water meter

esp8266:
  board: d1_mini
  restore_from_flash: true

preferences:
  flash_write_interval: 60min

api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

    # Enable fallback hotspot (captive portal) in case wifi connection fails
  reboot_timeout: 15min
  ap:
    ssid: ""
    password: ""
    # The following 4 lines corrected an issue I expirenced with the TinyS3 not being able to connect to wifi due to an "auth failure'/timeout. No idea why, but it worked. 
  power_save_mode: none
  enable_on_boot: True
  fast_connect: On
  output_power: 8.5

captive_portal:
    

packages:
  # water_meter: !include
  #   file: esphome-water-meter.yaml
  water_meter:
    url: https://github.com/erwyman/esphome-magnetometer-water-gas-meter
    ref: main
    file: esphome-water-meter.yaml
    refresh: 0s
